language: node_js

node_js:
  - "6"
  - "8"

cache: yarn

sudo: false

notifications:
  email: false

before_script:
  - yarn run lint

script:
  - yarn test:cover
  - yarn danger ci

after_success:
  - yarn run test:cover:CI
